jobs:
  build:
    name: Build with Java 17
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Check maven version
      run: mvn -v; echo "** ls **"; pwd && ls -l
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B install --file pom.xml
name: OpenPDF maven build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions:
  contents: read
